# Generated by Django 5.0.4 on 2024-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='titulo_eleitor',
            field=models.CharField(default='', max_length=12),
        ),
    ]
