# Generated by Django 5.0.4 on 2024-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_usuario_titulo_eleitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.CharField(default='', max_length=14),
        ),
    ]
