# Generated by Django 5.0.4 on 2024-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0004_remove_usuario_idade_usuario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='sem_email@exemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='Sem Endereço Cadastrado', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='Sem Telefone', max_length=20),
        ),
    ]
