# Generated by Django 5.0.4 on 2024-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0005_usuario_email_usuario_endereco_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado'), ('Viúvo', 'Viúvo')], default='Selecione', max_length=20),
        ),
    ]
