# Generated by Django 5.0.4 on 2024-05-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0006_usuario_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
