# Generated by Django 5.0.4 on 2024-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0011_alter_usuario_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_servico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
