# Generated by Django 5.0.4 on 2024-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0013_remove_usuario_tipo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_servico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
