# Generated by Django 5.0.4 on 2024-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0015_usuario_senha_gov'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='info_adicionais',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
