# Generated by Django 5.0.4 on 2024-05-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0018_alter_usuario_info_adicionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
