# Generated by Django 5.0.4 on 2024-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0019_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='titulo_eleitor',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
