# Generated by Django 5.0.4 on 2024-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0021_alter_usuario_documento_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='Sem Telefone', max_length=20, null=True),
        ),
    ]
